/**
 * 错误代码常量
 * 
 * 统一管理所有错误代码，便于错误处理和调试。
 * 错误代码按照功能模块分类，每个错误都有唯一的标识符。
 * 
 * @example
 * ```typescript
 * throw new AgentError('API密钥无效', ERROR_CODES.AGENT.INVALID_API_KEY);
 * ```
 */

export const ERROR_CODES = {
  // 智能体相关错误
  AGENT: {
    INIT_FAILED: 'AGENT_INIT_FAILED',
    NOT_INITIALIZED: 'AGENT_NOT_INITIALIZED',
    LLM_NOT_INITIALIZED: 'LLM_NOT_INITIALIZED',
    LLM_CALL_FAILED: 'LLM_CALL_FAILED',
    INVALID_API_KEY: 'INVALID_API_KEY',
    MAX_TURNS_EXCEEDED: 'MAX_TURNS_EXCEEDED',
    REACT_LOOP_FAILED: 'REACT_LOOP_FAILED',
    UNKNOWN_AGENT_TYPE: 'UNKNOWN_AGENT_TYPE',
    AGENT_CREATION_FAILED: 'AGENT_CREATION_FAILED',
    SIMPLE_AGENT_INIT_FAILED: 'SIMPLE_AGENT_INIT_FAILED',
    ORCHESTRA_AGENT_INIT_FAILED: 'ORCHESTRA_AGENT_INIT_FAILED',
    PLANNER_AGENT_NOT_INITIALIZED: 'PLANNER_AGENT_NOT_INITIALIZED',
    WORKER_AGENT_NOT_FOUND: 'WORKER_AGENT_NOT_FOUND',
    PLANNING_FAILED: 'PLANNING_FAILED',
    EXECUTION_FAILED: 'EXECUTION_FAILED',
    REPORTING_FAILED: 'REPORTING_FAILED'
  },

  // 工具相关错误
  TOOL: {
    NOT_FOUND: 'TOOL_NOT_FOUND',
    EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
    INVALID_PARAMETERS: 'TOOL_INVALID_PARAMETERS',
    LOAD_FAILED: 'TOOL_LOAD_FAILED',
    REGISTRATION_FAILED: 'TOOL_REGISTRATION_FAILED'
  },

  // 文件操作错误
  FILE: {
    READ_FAILED: 'FILE_READ_FAILED',
    WRITE_FAILED: 'FILE_WRITE_FAILED',
    DELETE_FAILED: 'FILE_DELETE_FAILED',
    NOT_FOUND: 'FILE_NOT_FOUND',
    ACCESS_DENIED: 'FILE_ACCESS_DENIED',
    INVALID_PATH: 'FILE_INVALID_PATH',
    OPERATION_FAILED: 'FILE_OPERATION_FAILED'
  },

  // 数据处理错误
  DATA: {
    INVALID_FORMAT: 'DATA_INVALID_FORMAT',
    PARSE_FAILED: 'DATA_PARSE_FAILED',
    CONVERSION_FAILED: 'DATA_CONVERSION_FAILED',
    ANALYSIS_FAILED: 'DATA_ANALYSIS_FAILED',
    UNSUPPORTED_OPERATION: 'DATA_UNSUPPORTED_OPERATION',
    UNSUPPORTED_FORMAT: 'DATA_UNSUPPORTED_FORMAT'
  },

  // 图像处理错误
  IMAGE: {
    NOT_FOUND: 'IMAGE_NOT_FOUND',
    INVALID_FORMAT: 'IMAGE_INVALID_FORMAT',
    PROCESSING_FAILED: 'IMAGE_PROCESSING_FAILED',
    GENERATION_FAILED: 'IMAGE_GENERATION_FAILED',
    ANALYSIS_FAILED: 'IMAGE_ANALYSIS_FAILED',
    UNSUPPORTED_OPERATION: 'IMAGE_UNSUPPORTED_OPERATION'
  },

  // 网络相关错误
  NETWORK: {
    REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
    TIMEOUT: 'NETWORK_TIMEOUT',
    CONNECTION_FAILED: 'NETWORK_CONNECTION_FAILED',
    INVALID_RESPONSE: 'NETWORK_INVALID_RESPONSE'
  },

  // 配置相关错误
  CONFIG: {
    INVALID_CONFIG: 'CONFIG_INVALID',
    MISSING_REQUIRED_FIELD: 'CONFIG_MISSING_REQUIRED_FIELD',
    LOAD_FAILED: 'CONFIG_LOAD_FAILED',
    VALIDATION_FAILED: 'CONFIG_VALIDATION_FAILED'
  },

  // 追踪相关错误
  TRACE: {
    SESSION_NOT_FOUND: 'TRACE_SESSION_NOT_FOUND',
    EXPORT_FAILED: 'TRACE_EXPORT_FAILED',
    UNSUPPORTED_FORMAT: 'TRACE_UNSUPPORTED_FORMAT'
  },

  // 通用错误
  COMMON: {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
    INVALID_INPUT: 'INVALID_INPUT',
    OPERATION_FAILED: 'OPERATION_FAILED'
  }
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES][keyof typeof ERROR_CODES[keyof typeof ERROR_CODES]];
