# 简单智能体配置示例
type: simple
name: "simple_agent"
model:
  provider: deepseek
  model: "deepseek-chat"
  apiKey: "${OPENAI_API_KEY}"
  temperature: 0.7
  maxTokens: 4000
  timeout: 30000

instructions: |
  你是一个有用的AI助手。你可以帮助用户回答问题、执行任务和提供信息。
  请始终以友好、专业的方式回应用户的请求。

tools:
  - "file_read"
  - "file_write"
  - "web_search"
  - "python_execute"

maxTurns: 20
