# Workforce Agent 配置示例
type: workforce
name: "workforce_agent"
model:
  provider: deepseek
  model: "deepseek-chat"
  apiKey: "${DEEPSEEK_API_KEY}"
  temperature: 0.7
  maxTokens: 4000

# Planner Agent 配置
workforcePlannerModel:
  provider: deepseek
  model: "deepseek-chat"
  apiKey: "${DEEPSEEK_API_KEY}"
  temperature: 0.3
  maxTokens: 2000

# Assigner Agent 配置
workforceAssignerModel:
  provider: deepseek
  model: "deepseek-chat"
  apiKey: "${DEEPSEEK_API_KEY}"
  temperature: 0.5
  maxTokens: 2000

# Answerer Agent 配置
workforceAnswererModel:
  provider: deepseek
  model: "deepseek-chat"
  apiKey: "${DEEPSEEK_API_KEY}"
  temperature: 0.5
  maxTokens: 3000

# 执行器智能体信息
workforceExecutorInfos:
  - name: "researcher"
    description: "信息研究员，负责收集和整理信息"
    strengths: ["网络搜索", "信息整理", "事实核查"]
    weaknesses: ["数据分析", "内容创作"]
  
  - name: "writer"
    description: "内容写作者，负责撰写和编辑内容"
    strengths: ["内容创作", "文案编辑", "结构化写作"]
    weaknesses: ["数据分析", "技术实现"]
  
  - name: "analyst"
    description: "数据分析师，负责数据处理和分析"
    strengths: ["数据分析", "统计计算", "可视化"]
    weaknesses: ["内容创作", "信息收集"]

# 执行器智能体配置
workforceExecutorAgents:
  researcher:
    type: simple
    name: "researcher"
    model:
      provider: deepseek
      model: "deepseek-chat"
      apiKey: "${DEEPSEEK_API_KEY}"
    tools: ["web_search", "file_read"]
    instructions: "你是一个专业的研究员，擅长收集和分析信息。"
  
  writer:
    type: simple
    name: "writer"
    model:
      provider: deepseek
      model: "deepseek-chat"
      apiKey: "${DEEPSEEK_API_KEY}"
    tools: ["file_write", "file_read"]
    instructions: "你是一个专业的写作者，擅长整理和撰写内容。"
  
  analyst:
    type: simple
    name: "analyst"
    model:
      provider: deepseek
      model: "deepseek-chat"
      apiKey: "${DEEPSEEK_API_KEY}"
    tools: ["python_execute", "file_read", "file_write"]
    instructions: "你是一个专业的数据分析师，擅长数据处理和分析。"

# 执行器配置
workforceExecutorConfig:
  maxTries: 3
  returnSummary: true

# 工具配置
tools:
  - "web_search"
  - "file_read"
  - "file_write"
  - "python_execute"

maxTurns: 50